#===============          ===============#
#=============== FIREWALL ===============#
#===============          ===============#

import atexit
from functools import wraps
import os
import threading
import time
from enum import Enum, auto
import socket
import struct
import json
import logging
from bcc import BPF
from dataclasses import dataclass

#========================================================================
# STANDALONE REPLACEMENTS FOR INTERNAL MODULE DEPENDENCIES
#========================================================================

logger = logging.getLogger("firewall")
logger.setLevel(logging.DEBUG)
if not logger.handlers:
    file_handler = logging.FileHandler("firewall.log")
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(file_handler)


class ModuleState(Enum):
    INIT = auto()
    STARTING = auto()
    RUNNING = auto()
    STOPPING = auto()
    STOPPED = auto()
    RESTARTING = auto()
    FAILED = auto()

class Module:
    """Abstract base class for system modules to manage layout and identification."""
    def module_name(self) -> str:
        pass
    def module_version(self) -> str:
        pass


class EventEmitter:
    """Simple internal event emitter to dispatch firewall events to registered listeners."""
    def __init__(self):
        self._listeners = []

    def add_listener(self, callback):
        self._listeners.append(callback)

    def event(self, event_obj):
        """Dispatches an event to all registered callbacks and logs it."""
        log_msg = f"[EVENT] {event_obj.format()}"
        if "FAILED" in event_obj.type.name or "DEAD" in event_obj.type.name:
            logger.error(log_msg)
        else:
            logger.info(log_msg)
        for listener in self._listeners:
            try:
                listener(event_obj)
            except Exception as e:
                logger.error(f"Error executing event listener: {e}")


class Exception(Exception):
    """Base application exception supporting severity layers and chaining causes."""
    class ExceptionSeverity(Enum):
        INFO = auto()
        WARNING = auto()
        ALERT = auto()
        CRITICAL = auto()

    def __init__(self, code, message, severity, cause=None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.severity = severity
        self.cause = cause

    def format(self) -> str:
        base = f"[{self.severity.name}] Code={self.code.name if self.code else 'NONE'} - {self.message}"
        if self.cause:
            base += f" | Cause: {str(self.cause)}"
        return base


class RecoveryManager:
    """Manages mapping between specific exceptions and their respective recovery actions."""
    def __init__(self):
        self._registry = {}

    def register(self, exception_cls, action):
        self._registry[exception_cls] = action

    def recover(self, exc):
        """Finds and executes the registered recovery strategy for a given exception."""
        action = self._registry.get(type(exc))
        if action:
            action.execute(exc)
            return True
        return False

    def recoverable(self, notify=None, rethrow=False):
        """Decorator to automatically catch exceptions and route them through the recovery engine."""
        def decorator(func):
            @wraps(func)
            def wrapper(*args, **kwargs):
                try:
                    return func(*args, **kwargs)
                except Exception as e:
                    if notify:
                        notify(*args, e)
                    # Attempt automated resolution
                    recovered = self.recover(e)
                    if not recovered or rethrow:
                        raise e
            return wrapper
        return decorator

recovery_manager = RecoveryManager()

#========================================================================
# FIREWALL LOGIC & DATA STRUCTURES
#========================================================================

MODULE_NAME = "Firewall"
MODULE_VERSION = "1.0"

class FirewallState(Enum):
    """Internal precise lifecycle states dedicated to the Firewall component."""
    INIT = ModuleState.INIT.value
    STARTING = ModuleState.STARTING.value
    RUNNING = ModuleState.RUNNING.value
    STOPPING = ModuleState.STOPPING.value
    STOPPED = ModuleState.STOPPED.value
    RESTARTING = ModuleState.RESTARTING.value
    FAILED = ModuleState.FAILED.value


class FirewallEventType(Enum):
    """Detailed telemetry event types generated by the firewall subsystem."""
    STATE_CHANGED = auto()
    RUNNING = auto()
    RUN_FAILED = auto()
    STARTING = auto()
    STARTED = auto()
    START_FAILED = auto()
    STOPPING = auto()
    STOPPED = auto()
    STOP_FAILED = auto()
    RESTARTING = auto()
    RESTARTED = auto()
    RESTART_FAILED = auto()
    CHECK_STARTED = auto()
    CHECK_OK = auto()
    CHECK_FAILED = auto()
    EBPF_LOAD_STARTED = auto()
    EBPF_LOADED = auto()
    EBPF_LOAD_FAILED = auto()
    EBPF_UNLOAD_STARTED = auto()
    EBPF_UNLOADED = auto()
    EBPF_UNLOAD_FAILED = auto()
    EBPF_CHECK_STARTED = auto()
    EBPF_CHECK_OK = auto()
    EBPF_CHECK_FAILED = auto()

    FIREWALL_NOT_LOADED = auto()
    BLOCK_IP_STARTED = auto()
    IP_BLOCKED = auto()
    BLOCK_IP_FAILED = auto()
    BLOCK_PORT_STARTED = auto()
    PORT_BLOCKED = auto()
    BLOCK_PORT_FAILED = auto()
    UNBLOCK_IP_STARTED = auto()
    IP_UNBLOCKED = auto()
    UNBLOCK_IP_FAILED = auto()
    UNBLOCK_PORT_STARTED = auto()
    PORT_UNBLOCKED = auto()
    UNBLOCK_PORT_FAILED = auto()
    RESET_RULES_STARTED = auto()
    RULES_RESETTED = auto()
    RESET_RULES_FAILED = auto()
    EXPORT_RULES_STARTED = auto()
    RULES_EXPORTED = auto()
    EXPORT_RULES_FAILED = auto()
    GET_STATS_STARTED = auto()
    STATS_GETTED = auto()
    GET_STATS_FAILED = auto()
    GET_IP_COUNTERS_STARTED = auto()
    IP_COUNTERS_GETTED = auto()
    GET_IP_COUNTERS_FAILED = auto()
    FIREWALL_THREAD_DEAD = auto()


@dataclass
class Event:
    """Abstract structural base representation for systemic telemetry tracking."""
    type: Enum
    source: str
    message: str | None = None
    payload: dict | None = None
    error: Exception | None = None
    code: Enum | None = None

    def format(self) -> str:
        """Serializes the core event properties into a human-readable log string."""
        parts = [f"Source={self.source}", f"Type={self.type.name}"]
        if self.message:
            parts.append(f"Msg={self.message}")
        if self.code:
            parts.append(f"Code={self.code.name}")
        if self.error:
            parts.append(f"Error={str(self.error)}")
        return " | ".join(parts)


@dataclass
class FirewallEvent(Event):
    """Firewall specialized event including contextual network details like rules or interfaces."""
    interface: str | None = None
    rule: dict | None = None
    stats: dict | None = None

    def __init__(
        self,
        type: FirewallEventType,
        message: str | None = None,
        interface: str | None = None,
        rule: dict | None = None,
        stats: dict | None = None,
        error: Exception | None = None,
        code: Enum | None = None,
        payload: dict | None = None,
    ):
        super().__init__(
            type=type,
            source="firewall",
            message=message,
            payload=payload,
            error=error,
            code=code,
        )
        self.interface = interface
        self.rule = rule
        self.stats = stats

    def format(self) -> str:
        """Extensions to the standard event serialization to include explicit rule parameters."""
        base = super().format()
        extra = []
        if self.interface:
            extra.append(f"Interface={self.interface}")
        if self.rule:
            extra.append(f"Rule={self.rule}")
        if self.stats:
            extra.append(f"Stats={self.stats}")

        if extra:
            return base + " | " + " | ".join(extra)
        return base


#=============== Exceptions System ===============#

class FirewallExceptionCode(Enum):
    """Error tracking identifier codes mapping directly to specific failures inside the firewall."""
    NO_ERROR = auto()
    FIREWALL_NOT_LOADED = auto()
    INVALID_IP_ADDRESS = auto()
    BLOCK_IP_FAILED = auto()
    UNBLOCK_IP_FAILED = auto()
    BLOCK_PORT_FAILED = auto()
    UNBLOCK_PORT_FAILED = auto()
    RESET_RULES_FAILED = auto()
    EXPORT_RULES_FAILED = auto()
    GET_STATS_FAILED = auto()
    GET_IP_COUNTERS_FAILED = auto()
    FIREWALL_THREAD_DEAD = auto()
    INVALID_STATE_TRANSITION = auto()


class FirewallException(Exception):
    """Polymorphic base exception handler wrapper for the eBPF Firewall component."""
    @staticmethod
    def format(exc: "FirewallException") -> str:
        """Appends technical runtime identifiers depending on what subclass exception is caught."""
        base = super(FirewallException, exc).format()
        extra = []

        if isinstance(exc, InvalidIPAddressException):
            extra.append(f"IP={exc.ip}")
        elif isinstance(exc, FirewallRuleOperationException):
            extra.append(f"Rule={exc.rule}")
        elif isinstance(exc, FirewallRoutineOperationException):
            extra.append(f"Operation={exc.operation}")

        if extra:
            base += " | " + " | ".join(extra)
        return base


class FirewallInvalidStateTransition(FirewallException):
    def __init__(self, message="Firewall invalid state transition"):
        super().__init__(
            code=FirewallExceptionCode.INVALID_STATE_TRANSITION,
            message=message,
            severity=Exception.ExceptionSeverity.ALERT
        )


class FirewallUnloadedException(FirewallException):
    def __init__(self, message="Firewall is not loaded"):
        super().__init__(
            code=FirewallExceptionCode.FIREWALL_NOT_LOADED,
            message=message,
            severity=Exception.ExceptionSeverity.ALERT
        )


class InvalidIPAddressException(FirewallException):
    def __init__(self, ip: str, cause: Exception | None = None):
        super().__init__(
            code=FirewallExceptionCode.INVALID_IP_ADDRESS,
            message=f"Invalid IP address: {ip}",
            severity=Exception.ExceptionSeverity.WARNING,
            cause=cause
        )
        self.ip = ip


class FirewallRuleOperationException(FirewallException):
    def __init__(self, code: FirewallExceptionCode, message: str, rule: dict | None = None, cause: Exception | None = None):
        super().__init__(
            code=code,
            message=message,
            severity=Exception.ExceptionSeverity.ALERT,
            cause=cause
        )
        self.rule = rule


class FirewallRoutineOperationException(FirewallException):
    def __init__(self, operation: str, message: str, cause: Exception | None = None):
        super().__init__(
            code=FirewallExceptionCode.NO_ERROR,
            message=f"Operation '{operation}' failed: {message}",
            severity=Exception.ExceptionSeverity.ALERT,
            cause=cause
        )
        self.operation = operation


class FirewallThreadException(FirewallException):
    def __init__(self, message="Firewall thread not alive"):
        super().__init__(
            code=FirewallExceptionCode.FIREWALL_THREAD_DEAD,
            message=message,
            severity=Exception.ExceptionSeverity.ALERT
        )


#=============== Automated Recovery Actions ===============#

class RecoveryAction:
    """Interface outlining executable self-healing strategies for trapped faults."""
    def execute(self, exc: Exception):
        pass

class FirewallRecoveryAction(RecoveryAction):
    """Context aware recovery base ensuring direct execution access to the active Firewall instance."""
    def __init__(self, firewall: "Firewall"):
        self.fw = firewall

class FirewallUnloadedRecoveryAction(FirewallRecoveryAction):
    def execute(self, exc: FirewallUnloadedException):
        """Attempts to dynamically reload the kernel hook maps if the driver drops out."""
        try:
            logger.warning("Recovery: Firewall unloaded. Attempting reloading.")
            self.fw.load()
        except Exception as e:
            logger.error(f"Recovery failed: {e}")
            self.fw.event(FirewallEvent(
                type=FirewallEventType.RESTART_FAILED,
                message="Firewall recovery restart failed",
                interface=self.fw.interface,
                error=e
            ))

class FirewallRuleRecoveryAction(FirewallRecoveryAction):
    def execute(self, exc: FirewallRuleOperationException):
        """Inverts failed operations to roll back dirty rules inside kernel space maps."""
        try:
            logger.warning(f"Recovery: Rule operation failed ({exc.code}). Attempting rollback.")
            if exc.rule:
                if exc.code == FirewallExceptionCode.BLOCK_IP_FAILED:
                    self.fw.unblock_ip(exc.rule.get("ip"))
                elif exc.code == FirewallExceptionCode.UNBLOCK_IP_FAILED:
                    self.fw.block_ip(exc.rule.get("ip"))
                elif exc.code == FirewallExceptionCode.BLOCK_PORT_FAILED:
                    self.fw.unblock_port(exc.rule.get("port"), exc.rule.get("proto", "tcp"))
                elif exc.code == FirewallExceptionCode.UNBLOCK_PORT_FAILED:
                    self.fw.block_port(exc.rule.get("port"), exc.rule.get("proto", "tcp"))
        except Exception as e:
            logger.error(f"Recovery failed for rule rollback: {e}")
            self.fw.event(FirewallEvent(
                type=FirewallEventType.RESET_RULES_FAILED,
                message="Rule recovery rollback failed",
                interface=self.fw.interface,
                rule=exc.rule,
                error=e
            ))

class FirewallRoutineRecoveryAction(FirewallRecoveryAction):
    def execute(self, exc: FirewallRoutineOperationException):
        """Forces a hard system reset sequence if structural procedures break mid-execution."""
        try:
            logger.warning(f"Recovery: Routine operation '{exc.operation}' failed. Attempting restart.")
            self.fw.restart()
        except Exception as e:
            logger.error(f"Recovery failed for routine: {e}")
            self.fw.event(FirewallEvent(
                type=FirewallEventType.RESTART_FAILED,
                message=f"Routine recovery for {exc.operation} failed",
                interface=self.fw.interface,
                error=e
            ))

class InvalidIPRecoveryAction(FirewallRecoveryAction):
    def execute(self, exc: InvalidIPAddressException):
        """Signals administrator awareness logs since string data formatting cannot be guessed automatically."""
        logger.warning(f"Invalid IP provided: {exc.ip}. Manual administrative parsing required.")

class FirewallThreadRecoveryAction(FirewallRecoveryAction):
    def execute(self, exc: FirewallThreadException):
        """Respawns the passive background monitoring daemon loop if it encounters unexpected crashes."""
        try:
            logger.warning("Recovery: Firewall thread dead. Attempting to restart thread.")
            with self.fw._lifecycle_lock:
                if self.fw._thread is None or not self.fw._thread.is_alive():
                    self.fw._stop_event.clear()
                    self.fw._thread = threading.Thread(
                        target=self.fw.run,
                        name="FirewallThread",
                        daemon=True
                    )
                    self.fw._thread.start()

            self.fw.event(FirewallEvent(
                type=FirewallEventType.RESTARTED,
                message="Firewall thread successfully restarted",
                interface=self.fw.interface
            ))
            logger.info("Firewall thread restarted successfully.")
        except Exception as e:
            logger.error(f"Firewall thread recovery failed: {e}")
            self.fw.event(FirewallEvent(
                type=FirewallEventType.RESTART_FAILED,
                message="Failed to recover firewall thread",
                interface=self.fw.interface,
                error=e
            ))


#=============== MAIN FIREWALL COMPONENT ===============#

class Firewall(EventEmitter, Module):
    """
    Asynchronous eBPF Express Data Path (XDP) Linux kernel spaces automated network firewall.
    Leverages BCC bindings to inject rule maps straight into kernel processing layers.
    """

    # Valid lifecycle finite state machine transition matrices
    VALID_STATE_TRANSITIONS = {
        FirewallState.INIT: {FirewallState.STARTING},
        FirewallState.STARTING: {FirewallState.RUNNING, FirewallState.FAILED},
        FirewallState.RUNNING: {FirewallState.STOPPING, FirewallState.RESTARTING, FirewallState.FAILED},
        FirewallState.STOPPING: {FirewallState.STOPPED, FirewallState.FAILED},
        FirewallState.STOPPED: {FirewallState.STARTING, FirewallState.RESTARTING},
        FirewallState.RESTARTING: {FirewallState.RUNNING, FirewallState.FAILED},
        FirewallState.FAILED: {FirewallState.RESTARTING, FirewallState.STOPPING},
    }
    
    def __init__(
        self,
        interface: str,
        ebpf_c_file: str,
        run_cycle: int = 5,

        # Standard callback hooks execution registration slots
        on_start: callable | None = None,
        on_start_fail: callable | None = None,
        on_run: callable | None = None,
        on_run_fail: callable | None = None,
        on_stop: callable | None = None,
        on_stop_fail: callable | None = None,
        on_restart: callable | None = None,
        on_restart_fail: callable | None = None,
        on_check: callable | None = None,
        on_check_fail: callable | None = None,
        on_load: callable | None = None,
        on_load_fail: callable | None = None,
        on_unload: callable | None = None,
        on_unload_fail: callable | None = None,
        on_block_ip: callable | None = None,
        on_unblock_ip: callable | None = None,
        on_block_port: callable | None = None,
        on_unblock_port: callable | None = None,
        on_reset_rules: callable | None = None,
        on_export_rules: callable | None = None,
        on_stats_read: callable | None = None,
        on_ip_counters_read: callable | None = None,
        on_block_ip_fail: callable | None = None,
        on_unblock_ip_fail: callable | None = None,
        on_block_port_fail: callable | None = None,
        on_unblock_port_fail: callable | None = None,
        on_reset_rules_fail: callable | None = None,
        on_export_rules_fail: callable | None = None,
        on_stats_read_fail: callable | None = None,
        on_ip_counters_read_fail: callable | None = None
    ):
        super().__init__()
        self.interface = interface
        self.ebpf_c_file = ebpf_c_file
        self.run_cycle = run_cycle

        # Assign functional pipeline callback mappings
        self.on_run = on_run
        self.on_run_fail = on_run_fail
        self.on_start = on_start
        self.on_start_fail = on_start_fail
        self.on_stop = on_stop
        self.on_stop_fail = on_stop_fail
        self.on_restart = on_restart
        self.on_restart_fail = on_restart_fail
        self.on_check = on_check
        self.on_check_fail = on_check_fail
        self.on_load = on_load
        self.on_load_fail = on_load_fail
        self.on_unload = on_unload
        self.on_unload_fail = on_unload_fail
        self.on_block_ip = on_block_ip
        self.on_block_ip_fail = on_block_ip_fail
        self.on_unblock_ip = on_unblock_ip
        self.on_unblock_ip_fail = on_unblock_ip_fail
        self.on_block_port = on_block_port
        self.on_block_port_fail = on_block_port_fail        
        self.on_unblock_port = on_unblock_port
        self.on_unblock_port_fail = on_unblock_port_fail
        self.on_reset_rules = on_reset_rules
        self.on_reset_rules_fail = on_reset_rules_fail
        self.on_stats_read = on_stats_read
        self.on_stats_read_fail = on_stats_read_fail
        self.on_export_rules = on_export_rules
        self.on_export_rules_fail = on_export_rules_fail
        self.on_ip_counters_read = on_ip_counters_read
        self.on_ip_counters_read_fail = on_ip_counters_read_fail

        # Thread management execution fields
        self._thread = None
        self._stop_event = threading.Event()
        self._lifecycle_lock = threading.Lock()
        self._ebpf_lock = threading.Lock()

        # BCC program engine context parameters
        self.bpf: BPF | None = None
        self.loaded = False

        # Graceful cleanup registration during unexpected processes terminations
        atexit.register(self.stop)
        self._state: FirewallState = FirewallState.INIT

    @property
    def state(self) -> FirewallState:
        return self._state

    @state.setter
    def state(self, new_state: FirewallState):
        self._state = new_state

    def set_state(self, new_state: FirewallState):
        """Thread safe handling changing state parameters with explicit audit logging event emissions."""
        old = self._state
        self.state = new_state
        if old != self._state:
            self.event(FirewallEvent(
                type=FirewallEventType.STATE_CHANGED,
                message=f"{old.name} → {self._state.name}",
                interface=self.interface
            ))

    def snapshot(self) -> dict:
        """Serializes current states and kernel configurations for synchronization records."""
        return {
            "module": {
                "name": "firewall",
                "version": "1.0",
                "module_state": self.state.name
            },
            "state": self.state.name,
            "config": {
                "interface": self.interface,
                "ebpf_c_file": self.ebpf_c_file,
                "run_cycle": self.run_cycle
            },
            "ebpf": {
                "loaded": self.loaded
            },
            "rules": {
                "blocked_ips": list(self.bpf["blocked_ips"].keys()) if self.bpf else [],
                "blocked_tcp_ports": list(self.bpf["blocked_tcp_ports"].keys()) if self.bpf else [],
                "blocked_udp_ports": list(self.bpf["blocked_udp_ports"].keys()) if self.bpf else []
            }
        }

    def restore(self, state: dict):
        """Restores module configurations and tracking vectors from structured JSON representations."""
        module_info = state.get("module", {})
        saved_state = module_info.get("module_state")
        if saved_state:
            self.state = FirewallState[saved_state]

        config = state.get("config", {})
        self.interface = config.get("interface", self.interface)
        self.ebpf_c_file = config.get("ebpf_c_file", self.ebpf_c_file)
        self.run_cycle = config.get("run_cycle", self.run_cycle)

        ebpf_info = state.get("ebpf", {})
        self.loaded = ebpf_info.get("loaded", False)

    def require_state(*allowed_states):
        """Validates operation calls against permissible matrices of Finite State Engine."""
        def decorator(func):
            @wraps(func)
            def wrapper(self, *args, **kwargs):
                if self.state not in allowed_states:
                    raise FirewallInvalidStateTransition(
                        f"Operation '{func.__name__}' not allowed in state {self.state.name}"
                    )
                return func(self, *args, **kwargs)
            return wrapper
        return decorator

    def module_name(self) -> str:
        return MODULE_NAME

    def module_version(self) -> str:
        return MODULE_VERSION

    def exception(self, e: Exception):
        """Target handler callback for automated recovery engine reporting failures."""
        self.event(FirewallEvent(
            type=FirewallEventType.RUN_FAILED,
            message="Firewall runtime cycle crashed",
            interface=self.interface,
            error=e
        ))
    
    def is_loaded(self) -> bool:
        return self.loaded and self.bpf

    @recovery_manager.recoverable(notify=exception, rethrow=False)
    def run(self):
        """Background continuous thread polling loop inspecting health contexts periodically."""
        while not self._stop_event.is_set():
            self.event(FirewallEvent(
                type=FirewallEventType.RUNNING,
                message="Firewall runtime loop execution tick",
                interface=self.interface
            ))
            if self.on_run:
                self.on_run()
            self.check()
            time.sleep(self.run_cycle)

    @require_state(FirewallState.STOPPED, FirewallState.FAILED, FirewallState.INIT)
    def start(self):
        """Compiles, links and injects native C driver codes right into target network interface devices."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.STARTING,
                interface=self.interface
            ))

            with self._lifecycle_lock:
                if self.on_start:
                    self.on_start()

                self.load()

                self._stop_event.clear()
                self._thread = threading.Thread(
                    target=self.run,
                    name="FirewallThread",
                    daemon=True
                )
                self._thread.start()
                self.set_state(FirewallState.RUNNING)

            self.event(FirewallEvent(
                type=FirewallEventType.STARTED,
                interface=self.interface
            ))

        except Exception as e:
            self.set_state(FirewallState.FAILED)
            logger.error(f"Startup procedure hit a fatal wall: {e}")
            exc = FirewallRoutineOperationException(
                operation="start",
                message=str(e),
                cause=e
            )
            self.event(FirewallEvent(
                type=FirewallEventType.START_FAILED,
                interface=self.interface,
                error=exc,
                code=getattr(e, "code", None)
            ))
            if self.on_start_fail:
                self.on_start_fail(exc)
            raise exc

    @require_state(FirewallState.RUNNING, FirewallState.RESTARTING)
    def stop(self):
        """Unlinks memory drivers from the adapter interfaces to return processing routes to kernel defaults."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.STOPPING,
                interface=self.interface
            ))

            with self._lifecycle_lock:
                self._stop_event.set()

                if self._thread:
                    try:
                        self._thread.join(timeout=3)
                    except Exception as e:
                        raise FirewallRoutineOperationException(
                            operation="stop",
                            message="Background monitor loop thread join sequence timed out",
                            cause=e
                        )
                    self._thread = None

                self.unload()

            if self.on_stop:
                self.on_stop()

            self.set_state(FirewallState.STOPPED)

            self.event(FirewallEvent(
                type=FirewallEventType.STOPPED,
                interface=self.interface
            ))

        except Exception as e:
            self.set_state(FirewallState.FAILED)
            logger.error(f"Shutdown routine broke unexpectedly: {e}")
            exc = FirewallRoutineOperationException(
                operation="stop",
                message=str(e),
                cause=e
            )
            self.event(FirewallEvent(
                type=FirewallEventType.STOP_FAILED,
                interface=self.interface,
                error=exc
            ))
            if self.on_stop_fail:
                self.on_stop_fail(exc)
            raise exc

    @require_state(FirewallState.RUNNING, FirewallState.FAILED)
    def restart(self):
        """Synchronously processes systemic reset sequences to redeploy compiled eBPF code assets."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.RESTARTING,
                interface=self.interface
            ))

            self.stop()
            self.start()
            
            if self.on_restart:
                self.on_restart()

            self.event(FirewallEvent(
                type=FirewallEventType.RESTARTED,
                interface=self.interface
            ))

            self.set_state(FirewallState.RUNNING)

        except Exception as e:
            self.set_state(FirewallState.FAILED)
            logger.error(f"Module structural recycle sequence failed entirely: {e}")
            exc = FirewallRoutineOperationException(
                operation="restart",
                message=str(e),
                cause=e
            )
            self.event(FirewallEvent(
                type=FirewallEventType.RESTART_FAILED,
                interface=self.interface,
                error=exc
            ))
            if self.on_restart_fail:
                self.on_restart_fail(exc)
            raise exc
    
    def check_ebpf(self, raiseExc: bool = True):
        """Verifies integrity status tracking metrics of BCC virtual map hooks allocations."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.EBPF_CHECK_STARTED,
                interface=self.interface
            ))

            if not self.loaded or not self.bpf:
                exc = FirewallUnloadedException("eBPF microcode maps are missing or unallocated")
                self.event(FirewallEvent(
                    type=FirewallEventType.FIREWALL_NOT_LOADED,
                    interface=self.interface,
                    error=exc
                ))
                raise exc

            self.event(FirewallEvent(
                type=FirewallEventType.EBPF_CHECK_OK,
                interface=self.interface
            ))
            return True

        except Exception as e:
            logger.error(f"Kernel layer hook validation failure detected: {e}")
            exc = FirewallRoutineOperationException(
                operation="check_ebpf",
                message=str(e),
                cause=e
            )
            self.event(FirewallEvent(
                type=FirewallEventType.EBPF_CHECK_FAILED,
                interface=self.interface,
                error=exc
            ))
            if raiseExc:
                raise exc
            return False, exc
            
    def check(self, raiseExc: bool = True):
        """Full systematic diagnostic cycle validating both eBPF states and background threads health."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.CHECK_STARTED,
                interface=self.interface
            ))

            self.check_ebpf()

            with self._lifecycle_lock:
                if not self._thread or not self._thread.is_alive():
                    exc = FirewallThreadException("Firewall polling thread became unresponsive or died")
                    self.event(FirewallEvent(
                        type=FirewallEventType.FIREWALL_THREAD_DEAD,
                        interface=self.interface,
                        error=exc
                    ))
                    raise exc

            if self.on_check:
                self.on_check()

            self.event(FirewallEvent(
                type=FirewallEventType.CHECK_OK,
                interface=self.interface
            ))
            return True

        except Exception as e:
            logger.error(f"System structural diagnostics detected errors: {e}")
            exc = FirewallRoutineOperationException(
                operation="check",
                message=str(e),
                cause=e
            )
            self.event(FirewallEvent(
                type=FirewallEventType.CHECK_FAILED,
                interface=self.interface,
                error=exc
            ))
            if self.on_check_fail:
                self.on_check_fail(exc)
            if raiseExc:
                raise exc
            return False, exc

    def load(self):
        """Parses local raw C files, builds BPF bytecodes and binds it directly to XDP network frames ingestion."""
        with self._ebpf_lock:
            try:
                self.event(FirewallEvent(
                    type=FirewallEventType.EBPF_LOAD_STARTED,
                    interface=self.interface
                ))

                if not os.path.exists(self.ebpf_c_file):
                    raise FirewallRoutineOperationException(
                        operation="load",
                        message=f"Target eBPF source file path '{self.ebpf_c_file}' not reachable"
                    )

                # Initialize runtime BCC driver instances
                self.bpf = BPF(src_file=self.ebpf_c_file)
                fn = self.bpf.load_func("xdp_firewall", BPF.XDP)
                self.bpf.attach_xdp(self.interface, fn, 0)
                
                # Configure default firewall behavior (e.g., policy index 0 set to allow/pass by default)
                self.bpf["default_policy"][0] = 1
                self.loaded = True

                if self.on_load:
                    self.on_load()

                self.event(FirewallEvent(
                    type=FirewallEventType.EBPF_LOADED,
                    interface=self.interface
                ))

            except Exception as e:
                logger.error(f"Failed loading virtual system layer hooks: {e}")
                exc = FirewallRoutineOperationException(
                    operation="load",
                    message=str(e),
                    cause=e
                )
                self.event(FirewallEvent(
                    type=FirewallEventType.EBPF_LOAD_FAILED,
                    interface=self.interface,
                    error=exc
                ))
                if self.on_load_fail:
                    self.on_load_fail(exc)
                raise exc

    def unload(self):
        """Detaches raw XDP programs from network layer interfaces securely cleaning memory handles."""
        with self._ebpf_lock:
            try:
                self.event(FirewallEvent(
                    type=FirewallEventType.EBPF_UNLOAD_STARTED,
                    interface=self.interface
                ))

                if self.bpf:
                    try:
                        self.bpf.remove_xdp(self.interface, 0)
                    except Exception as e:
                        raise FirewallRoutineOperationException(
                            operation="unload",
                            message="Forced interface unlinking detachment sequence rejected by kernel",
                            cause=e
                        )
                    finally:
                        self.bpf = None
                        self.loaded = False

                if self.on_unload:
                    self.on_unload()

                self.event(FirewallEvent(
                    type=FirewallEventType.EBPF_UNLOADED,
                    interface=self.interface
                ))

            except Exception as e:
                logger.error(f"Encountered errors offloading components from device interface drivers: {e}")
                exc = e if isinstance(e, FirewallException) else FirewallRoutineOperationException(
                    operation="unload",
                    message=str(e),
                    cause=e
                )
                self.event(FirewallEvent(
                    type=FirewallEventType.EBPF_UNLOAD_FAILED,
                    interface=self.interface,
                    error=exc
                ))
                if self.on_unload_fail:
                    self.on_unload_fail(exc)
                raise exc

    def ip_to_u32(self, ip: str) -> int:
        """Converts human standard dot decimal string IPs into unsigned 32-bit big endian integer network maps keys."""
        try:
            return struct.unpack("I", socket.inet_aton(ip))[0]
        except OSError as e:
            logger.error(f"IP format parsing failure on: {ip}")
            raise InvalidIPAddressException(ip=ip, cause=e)

    @require_state(FirewallState.RUNNING)
    def block_ip(self, ip: str):
        """Pushes parsed network target integers inside active eBPF map hash lists to drop matching incoming packets."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.BLOCK_IP_STARTED,
                message=f"Request received to filter IP traffic from: {ip}",
                interface=self.interface
            ))

            if not self.loaded or self.bpf is None:
                raise FirewallUnloadedException(message=f"Cannot append filter for IP {ip}: subsystem offline")

            ip_u32 = self.ip_to_u32(ip)
            self.bpf["blocked_ips"][ip_u32] = 1

            if self.on_block_ip:
                self.on_block_ip(ip)

            self.event(FirewallEvent(
                type=FirewallEventType.IP_BLOCKED,
                message=f"IP structure {ip} recorded inside kernel filters successfully",
                interface=self.interface
            ))

        except Exception as e:
            logger.error(f"Rule generation execution failed for target IP: {ip}. Details: {e}")
            self.event(FirewallEvent(
                type=FirewallEventType.BLOCK_IP_FAILED,
                message=f"Processing error during filtering layout setups for: {ip}",
                error=e,
                interface=self.interface
            ))
            if self.on_block_ip_fail:
                self.on_block_ip_fail(e)
            raise FirewallRuleOperationException(
                code=FirewallExceptionCode.BLOCK_IP_FAILED,
                message=f"Execution block sequence dropped on target host address: '{ip}'",
                rule={"ip": ip},
                cause=e
            )

    @require_state(FirewallState.RUNNING)
    def unblock_ip(self, ip: str):
        """Evicts recorded ip tracking keys out from active kernel space map allocations."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.UNBLOCK_IP_STARTED,
                message=f"Request received to restore access routines for host: {ip}",
                interface=self.interface
            ))

            if not self.loaded or self.bpf is None:
                raise FirewallUnloadedException(message=f"Cannot remove filter rule for IP {ip}: subsystem offline")

            ip_u32 = self.ip_to_u32(ip)
            del self.bpf["blocked_ips"][ip_u32]

            if self.on_unblock_ip:
                self.on_unblock_ip(ip)

            self.event(FirewallEvent(
                type=FirewallEventType.IP_UNBLOCKED,
                message=f"Traffic paths restored successfully for address: {ip}",
                interface=self.interface
            ))

        except Exception as e:
            logger.error(f"Rule destruction failure encountered for target IP: {ip}. Details: {e}")
            self.event(FirewallEvent(
                type=FirewallEventType.UNBLOCK_IP_FAILED,
                message=f"Processing failure handling whitelist rule modifications on host: {ip}",
                error=e,
                interface=self.interface
            ))
            if self.on_unblock_ip_fail:
                self.on_unblock_ip_fail(e)
            raise FirewallRuleOperationException(
                code=FirewallExceptionCode.UNBLOCK_IP_FAILED,
                message=f"Execution clear rule command aborted on address target: '{ip}'",
                rule={"ip": ip},
                cause=e
            )

    @require_state(FirewallState.RUNNING)
    def block_port(self, port: int, proto: str = "tcp"):
        """Restricts specific port bindings endpoints by inserting structural keys into transport filtering arrays."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.BLOCK_PORT_STARTED,
                message=f"Request received to filter port: {port} over protocol: {proto}",
                interface=self.interface
            ))

            if not self.loaded or self.bpf is None:
                raise FirewallUnloadedException(message="Cannot apply port filters: eBPF engine is offline")

            table = "blocked_tcp_ports" if proto.lower() == "tcp" else "blocked_udp_ports"
            self.bpf[table][port] = 1

            if self.on_block_port:
                self.on_block_port(port, proto)

            self.event(FirewallEvent(
                type=FirewallEventType.PORT_BLOCKED,
                message=f"Network port destination target {port}/{proto} locked successfully",
                interface=self.interface
            ))

        except Exception as e:
            logger.error(f"Execution failed injecting protocol filtering records on port: {port}. Details: {e}")
            self.event(FirewallEvent(
                type=FirewallEventType.BLOCK_PORT_FAILED,
                message=f"Internal exception intercepting pipeline execution configurations on port: {port}",
                error=e,
                interface=self.interface
            ))
            if self.on_block_port_fail:
                self.on_block_port_fail(e)
            raise FirewallRuleOperationException(
                code=FirewallExceptionCode.BLOCK_PORT_FAILED,
                message=f"System failed blocking port target configurations: '{port}' ({proto})",
                rule={"port": port, "proto": proto},
                cause=e
            )

    @require_state(FirewallState.RUNNING)
    def unblock_port(self, port: int, proto: str = "tcp"):
        """Clears specific transport targets from kernel spaces arrays to re-allow communication channels."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.UNBLOCK_PORT_STARTED,
                message=f"Request received to release port interface block rule on: {port} ({proto})",
                interface=self.interface
            ))

            if not self.loaded or self.bpf is None:
                raise FirewallUnloadedException(message="Cannot drop port constraint mappings: drivers are missing")

            table = "blocked_tcp_ports" if proto.lower() == "tcp" else "blocked_udp_ports"
            del self.bpf[table][port]

            if self.on_unblock_port:
                self.on_unblock_port(port, proto)

            self.event(FirewallEvent(
                type=FirewallEventType.PORT_UNBLOCKED,
                message=f"Communication lines re-opened on destination port: {port}/{proto}",
                interface=self.interface
            ))

        except Exception as e:
            logger.error(f"Failed clearing protocol constraint structures on port mapping: {port}. Details: {e}")
            self.event(FirewallEvent(
                type=FirewallEventType.UNBLOCK_PORT_FAILED,
                message=f"Encountered system fault unblocking interface endpoints: {port}",
                error=e,
                interface=self.interface
            ))
            if self.on_unblock_port_fail:
                self.on_unblock_port_fail(e)
            raise FirewallRuleOperationException(
                code=FirewallExceptionCode.UNBLOCK_PORT_FAILED,
                message=f"System failed flushing interface tracking rules from port resource: '{port}'",
                rule={"port": port, "proto": proto},
                cause=e
            )

    @require_state(FirewallState.RUNNING)
    def reset_rules(self):
        """Wipes out all recorded values from every single kernel eBPF rule map simultaneously."""
        try:
            self.event(FirewallEvent(
                type=FirewallEventType.RESET_RULES_STARTED,
                message="Global clearance command dispatched for all firewall lookup registries",
                interface=self.interface
            ))

            if not self.loaded or self.bpf is None:
                raise FirewallUnloadedException(message="Cannot flush table allocations: system engine offline")

            self.bpf["blocked_ips"].clear()
            self.bpf["blocked_tcp_ports"].clear()
            self.bpf["blocked_udp_ports"].clear()

            if self.on_reset_rules:
                self.on_reset_rules()

            self.event(FirewallEvent(
                type=FirewallEventType.RULES_RESETTED,
                message="All dynamic kernel space filter maps flushed to clean defaults successfully",
                interface=self.interface
            ))

        except Exception as e:
            logger.error(f"Global dynamic table clearance hit an unrecoverable failure: {e}")
            self.event(FirewallEvent(
                type=FirewallEventType.RESET_RULES_FAILED,
                message="Fatal processing failure during database memory maps wipe out routines",
                error=e,
                interface=self.interface
            ))
            if self.on_reset_rules_fail:
                self.on_reset_rules_fail(e)
            raise FirewallRuleOperationException(
                code=FirewallExceptionCode.RESET_RULES_FAILED,
                message="Global database memory array flush aborted due to kernel response faults",
                cause=e
            )
        
    @require_state(FirewallState.RUNNING)
    def export_rules(self, path: str):
        """Reads kernel arrays structures, parses keys back into human format and writes them to local disk files."""
        with self._lifecycle_lock:
            with self._ebpf_lock:
                try:
                    self.event(FirewallEvent(
                        type=FirewallEventType.EXPORT_RULES_STARTED,
                        message=f"Marshalling runtime network rules maps directly onto file: {path}",
                        interface=self.interface
                    ))

                    if not self.loaded or self.bpf is None:
                        raise FirewallUnloadedException(message="Export aborted: engine maps are missing from memory")

                    data = {
                        "blocked_ips": [
                            socket.inet_ntoa(struct.pack("I", k.value))
                            for k in self.bpf["blocked_ips"].keys()
                        ],
                        "blocked_tcp_ports": [
                            int(k.value)
                            for k in self.bpf["blocked_tcp_ports"].keys()
                        ],
                        "blocked_udp_ports": [
                            int(k.value)
                            for k in self.bpf["blocked_udp_ports"].keys()
                        ],
                    }

                    with open(path, "w") as f:
                        json.dump(data, f, indent=2)

                    if self.on_export_rules:
                        self.on_export_rules(path)

                    self.event(FirewallEvent(
                        type=FirewallEventType.RULES_EXPORTED,
                        message=f"Network topology configuration logs exported smoothly to storage target: {path}",
                        interface=self.interface
                    ))

                except Exception as e:
                    logger.error(f"Failed exporting configuration snapshots onto persistent storage path: {path}. Details: {e}")
                    self.event(FirewallEvent(
                        type=FirewallEventType.EXPORT_RULES_FAILED,
                        message=f"I/O runtime mapping exception encountered writing configuration states to path: {path}",
                        error=e,
                        interface=self.interface
                    ))
                    if self.on_export_rules_fail:
                        self.on_export_rules_fail(e)
                    raise FirewallRuleOperationException(
                        code=FirewallExceptionCode.EXPORT_RULES_FAILED,
                        message=f"Configuration file generation failure encountered targeting file system layout at: '{path}'",
                        cause=e
                    )

    @require_state(FirewallState.RUNNING)
    def get_stats(self) -> dict:
        """Retrieves global telemetry packets counters indicating dropped vs accepted flows since startup loops."""
        with self._lifecycle_lock:
            with self._ebpf_lock:
                try:
                    self.event(FirewallEvent(
                        type=FirewallEventType.GET_STATS_STARTED,
                        message="Reading global packet traffic metrics counters out from virtual driver registers",
                        interface=self.interface
                    ))

                    if not self.loaded or self.bpf is None:
                        raise FirewallUnloadedException(message="Telemetry extraction aborted: system components offline")

                    stats_map = self.bpf["stats"]
                    # Index 0 tracks globally allowed frames, Index 1 tracks dropped violations
                    allowed = int(stats_map[0].value) if 0 in stats_map else 0
                    dropped = int(stats_map[1].value) if 1 in stats_map else 0

                    stats = {
                        "allowed": allowed,
                        "dropped": dropped,
                        "total": allowed + dropped
                    }

                    if self.on_stats_read:
                        self.on_stats_read(stats)

                    self.event(FirewallEvent(
                        type=FirewallEventType.STATS_GETTED,
                        message="Telemetry counter information compiled safely from kernel spaces",
                        interface=self.interface
                    ))
                    return stats

                except Exception as e:
                    logger.error(f"Failed pulling packet processing performance analytics out from core driver: {e}")
                    self.event(FirewallEvent(
                        type=FirewallEventType.GET_STATS_FAILED,
                        message="Error encountered pulling traffic data statistics logs from inner device registers",
                        error=e,
                        interface=self.interface
                    ))
                    if self.on_stats_read_fail:
                        self.on_stats_read_fail(e)
                    raise FirewallRuleOperationException(
                        code=FirewallExceptionCode.GET_STATS_FAILED,
                        message="Performance metrics collection pipeline dropped execution due to reading errors",
                        cause=e
                    )

    @require_state(FirewallState.RUNNING)
    def get_ip_counters(self) -> dict[str, int]:
        """Fetches individual traffic hit count statistics mapped out relative to individual incoming addresses."""
        with self._lifecycle_lock:
            with self._ebpf_lock:
                try:
                    self.event(FirewallEvent(
                        type=FirewallEventType.GET_IP_COUNTERS_STARTED,
                        message="Extracting individual address processing logs statistics out from dynamic tables",
                        interface=self.interface
                    ))

                    if not self.loaded or self.bpf is None:
                        raise FirewallUnloadedException(message="Operation aborted: component layout maps missing")

                    counters: dict[str, int] = {}
                    for k, v in self.bpf["ip_counters"].items():
                        ip = socket.inet_ntoa(struct.pack("I", k.value))
                        counters[ip] = int(v.value)

                    if self.on_ip_counters_read:
                        self.on_ip_counters_read(counters)

                    self.event(FirewallEvent(
                        type=FirewallEventType.IP_COUNTERS_GETTED,
                        message="Individual host hit analytics processed safely into data results tables",
                        interface=self.interface
                    ))
                    return counters

                except Exception as e:
                    logger.error(f"Failed pulling address traffic analytical counters out from eBPF tables: {e}")
                    self.event(FirewallEvent(
                        type=FirewallEventType.GET_IP_COUNTERS_FAILED,
                        message="Error reading connection hit records from volatile virtual analytics maps",
                        error=e,
                        interface=self.interface
                    ))
                    if self.on_ip_counters_read_fail:
                        self.on_ip_counters_read_fail(e)
                    raise FirewallRuleOperationException(
                        code=FirewallExceptionCode.GET_IP_COUNTERS_FAILED,
                        message="Host analytics reader sequence dropped processing execution due to memory map faults",
                        cause=e
                    )


#========================================================================
# INITIALIZATION & MODULE REGISTRATION WITH STANDALONE CONFIGURATION
#========================================================================

# Fallback values replacing 'environ' attributes if file is executed independently.
# Adjust these values to match your testing environment setup if needed.
DEFAULT_INTERFACE = os.getenv("FIREWALL_INTERFACE", "eth0")
DEFAULT_EBPF_FILE = os.getenv("FIREWALL_EBPF_C_FILE", "xdp_firewall.c")
DEFAULT_RUN_CYCLE = int(os.getenv("FIREWALL_RUN_CYCLE", "5"))

firewall = Firewall(
    interface=DEFAULT_INTERFACE,
    ebpf_c_file=DEFAULT_EBPF_FILE,
    run_cycle=DEFAULT_RUN_CYCLE
)

# Automated strategy assignment within our newly defined standalone recovery manager
recovery_manager.register(FirewallUnloadedException, FirewallUnloadedRecoveryAction(firewall))
recovery_manager.register(FirewallRuleOperationException, FirewallRuleRecoveryAction(firewall))
recovery_manager.register(FirewallRoutineOperationException, FirewallRoutineRecoveryAction(firewall))
recovery_manager.register(InvalidIPAddressException, InvalidIPRecoveryAction(firewall))
recovery_manager.register(FirewallThreadException, FirewallThreadRecoveryAction(firewall))